name: Sync Nacos Config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Debug Current Directory
        run: |
          echo "Current directory:"
          cd
          dir
      - name: Sync Nacos Config
        run: |
          $env:NAMESPACE_ID='zmy' # nacos中命名空间
          
          # 读取文件内容
          $content = Get-Content -Raw $filePath
          
          # 定义请求URL 和Body体
          function Sync-Config {
              param (
                  [string]$dataId,
                  [string]$filePath
              )
          
              $uri = "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=$dataId&group=DEV_GROUP&tenant=$env:NAMESPACE_ID"
              $body = @{ content = $content }
              Invoke-RestMethod -Method Post -Uri $uri -Body $body -ContentType "application/x-www-form-urlencoded"
              Write-Host "$dataId synced"
          }
          
          Sync-Config -dataId "application-common.yml" -filePath "nacosConfig\application-common.yml"
          Sync-Config -dataId "cloud-gateway-service.yml" -filePath "nacosConfig\cloud-gateway-service.yml"
          Sync-Config -dataId "cloud-sys-service.yml" -filePath "nacosConfig\cloud-sys-service.yml"
          Sync-Config -dataId "cloud-report-service.yml" -filePath "nacosConfig\cloud-report-service.yml"
