name: Sync Nacos Config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Debug Nacos Config File
        run: |
          echo "Current directory:"
          cd
          dir
      - name: Sync Nacos Config
        run: |
          $env:NAMESPACE_ID='zmy'
          
          echo Syncing application-common.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=application-common.yml&group=DEV_GROUP&tenant=$env:NAMESPACE_ID" ^
               -d "content=$(type \application-common.yml)"
          echo "application-common.yml synced"
          
          echo Syncing cloud-gateway-service.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=cloud-gateway-service.yml&group=DEV_GROUP&tenant=$env:NAMESPACE_ID" ^
               -d "content=$(type \cloud-gateway-service.yml)"
          echo "cloud-gateway-service.yml synced"
          
          echo Syncing cloud-sys-service.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=cloud-sys-service.yml&group=DEV_GROUP&tenant=$env:NAMESPACE_ID" ^
               -d "content=$(type \cloud-sys-service.yml)"
          echo "cloud-sys-service.yml synced"
          
          echo Syncing cloud-report-service.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=cloud-report-service.yml&group=DEV_GROUP&tenant=$env:NAMESPACE_ID" ^
               -d "content=$(type \cloud-report-service.yml)"
          echo "cloud-report-service.yml synced"
