name: Sync Nacos Config

on:
  push:
    paths:
      - 'nacosConfig/**'

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Nacos Config File
        run: |
          echo "Reading application-common.yml"
          type nacosConfig\application-common.yml
          echo "Reading cloud-gateway-service.yml"
          type nacosConfig\cloud-gateway-service.yml
          echo "Reading cloud-sys-service.yml"
          type nacosConfig\cloud-sys-service.yml
          echo "Reading cloud-report-service.yml"
          type nacosConfig\cloud-report-service.yml

      - name: Sync Nacos Config
        run: |
          NAMESPACE_ID='zmy'
          
          echo Syncing application-common.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=application-common.yml&group=DEV_GROUP&tenant=${NAMESPACE_ID}" ^
               -d "content=$(<nacosConfig\application-common.yml)"
          echo "application-common.yml synced"
          
          echo Syncing cloud-gateway-service.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=cloud-gateway-service.yml&group=DEV_GROUP&tenant=${NAMESPACE_ID}" ^
               -d "content=$(<nacosConfig\cloud-gateway-service.yml)"
          echo "cloud-gateway-service.yml synced"
          
          echo Syncing cloud-sys-service.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=cloud-sys-service.yml&group=DEV_GROUP&tenant=${NAMESPACE_ID}" ^
               -d "content=$(<nacosConfig\cloud-sys-service.yml)"
          echo "cloud-sys-service.yml synced"
          
          echo Syncing cloud-report-service.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=cloud-report-service.yml&group=DEV_GROUP&tenant=${NAMESPACE_ID}" ^
               -d "content=$(<nacosConfig\cloud-report-service.yml)"
          echo "cloud-report-service.yml synced"
