name: Sync Nacos Config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync Nacos Config
        run: |
          $env:NAMESPACE_ID='zmy'
          
          echo Syncing cloud-gateway-service.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=cloud-gateway-service.yml&group=DEV_GROUP&tenant=$env:NAMESPACE_ID" ^
               -d "content=$content"
          echo "cloud-gateway-service.yml synced"
          
          echo Syncing cloud-sys-service.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=cloud-sys-service.yml&group=DEV_GROUP&tenant=$env:NAMESPACE_ID" ^
               -d "content=$content"
          echo "cloud-sys-service.yml synced"
          
          echo Syncing cloud-report-service.yml...
          curl -X POST "http://192.168.1.142:8848/nacos/v1/cs/configs?dataId=cloud-report-service.yml&group=DEV_GROUP&tenant=$env:NAMESPACE_ID" ^
               -d "content=$(<nacosConfig\cloud-report-service.yml)"
          echo "cloud-report-service.yml synced"
